### ISSUE TITLE
OS X build broken or undocumented

### ISSUE THREAD

**Issue by cserb** [ripple/rippled#1900]
[The guide for building rippled on os x](https://wiki.ripple.com/OSX_Build_Instructions) is not up to date and trying to build it according to it is not working.

Setting the `BOOST_ROOT` helps and seems to work but setting `PROTOBUF_ROOT` (which is not mentioned as necessary in the guide) isn't working.

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
clang++ -o build/clang.release/src/ripple/unity/app_ledger.o -c -Wall -frtti -std=c++14 -Wno-invalid-offsetof -Wno-mismatched-tags -Wno-deprecated-register -Wno-unused-local-typedefs -Wno-unknown-warning-option -isystem/usr/local/Cellar/boost/1.62.0/include -Wno-sign-compare -Wno-char-subscripts -Wno-format -g -Wno-redeclared-class-member -Wno-deprecated -Wno-deprecated-declarations -Wno-unused-variable -Wno-unused-function -O3 -fno-strict-aliasing -DOPENSSL_NO_SSL2 -DDEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER -DHAVE_USLEEP=1 -DSOCI_CXX_C11=1 -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS -DBOOST_NO_AUTO_PTR -DNO_LOG_UNHANDLED_EXCEPTIONS -DNDEBUG -DBOOST_ASIO_HAS_STD_ARRAY -D_FILE_OFFSET_BITS=64 -DBEAST_COMPILE_OBJECTIVE_CPP=1 -I/usr/local/Cellar/openssl/1.0.2j/include -Isrc -Isrc/beast -Isrc/beast/include -Isrc/beast/extras -Ibuild/proto -Isrc/soci/src -Isrc/soci/include -I/usr/local/include/src src/ripple/unity/app_ledger.cpp
In file included from src/ripple/unity/app_ledger.cpp:24:
In file included from src/ripple/app/ledger/AccountStateSF.cpp:22:
In file included from src/ripple/app/ledger/LedgerMaster.h:40:
build/proto/ripple.pb.h:9:10: fatal error: 'google/protobuf/stubs/common.h' file not found
#include <google/protobuf/stubs/common.h>
         ^
1 error generated.
scons: *** [build/clang.release/src/ripple/unity/app_ledger.o] Error 1
scons: building terminated because of errors.
```

protobuf is installed as mentioned in the guide (also tried it via homebrew) and the files are also there

**Comment by mellery451** [comment]
Hi,
I believe this is related to the version of protobuf as rippled will only build with 2.5.x or 2.6.x right now. Can you please try this version?  https://github.com/google/protobuf/releases/tag/v2.6.1 - the build instructions should be the same if you use that version. I'm not sure the homebrew version can be used at this point (certainly latest will not work) both because of the version requirement AND the build flags we recommend when building protobuf.

**Comment by cserb** [comment]
The reason I installed the newest version of protobuf is that when trying to install 2.6.x autogen.sh is trying an old link to an old version of gtest and/or gmock. So autogen basically fails.

**Comment by mellery451** [comment]
I just downloaded 2.6.1 and built successfully - I don't see any errors related to gtest/gmock. It looks to me like the protobuf package has included gtest source as a subdirectory, so the version should be fixed as far as this source is concerned.

I'm going to correct the build instructions to be explicit about the protobuf version requirements for rippled (2.5 or 2.6). If there are local issues building those versions of protobuf, I think that might have to be addressed by the protobuf maintainers.

**Comment by cserb** [comment]
The package you pointed me to didn't contain gtest:

```
⋊> ~/D/protobuf-2.6.1 ./autogen.sh                                                                                                     10:38:11
Google Test not present.  Fetching gtest-1.5.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1586  100  1586    0     0   5581      0 --:--:-- --:--:-- --:--:--  5664
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
⋊> ~/D/protobuf-2.6.1 cat autogen.sh                                                                                                   10:38:30
#!/bin/sh

# Run this script to generate the configure script and other files that will
# be included in the distribution.  These files are not checked in because they
# are automatically generated.

set -e

# Check that we're being run from the right directory.
if test ! -f src/google/protobuf/stubs/common.h; then
  cat >&2 << __EOF__
Could not find source code.  Make sure you are running this script from the
root of the distribution tree.
__EOF__
  exit 1
fi

# Check that gtest is present.  Usually it is already there since the
# directory is set up as an SVN external.
if test ! -e gtest; then
  echo "Google Test not present.  Fetching gtest-1.5.0 from the web..."
  curl http://googletest.googlecode.com/files/gtest-1.5.0.tar.bz2 | tar jx
  mv gtest-1.5.0 gtest
fi

set -ex

# Temporary hack:  Must change C runtime library to "multi-threaded DLL",
#   otherwise it will be set to "multi-threaded static" when MSVC upgrades
#   the project file to MSVC 2005/2008.  vladl of Google Test says gtest will
#   probably change their default to match, then this will be unnecessary.
#   One of these mappings converts the debug configuration and the other
#   converts the release configuration.  I don't know which is which.
sed -i -e 's/RuntimeLibrary="5"/RuntimeLibrary="3"/g;
           s/RuntimeLibrary="4"/RuntimeLibrary="2"/g;' gtest/msvc/*.vcproj

# TODO(kenton):  Remove the ",no-obsolete" part and fix the resulting warnings.
autoreconf -f -i -Wall,no-obsolete

rm -rf autom4te.cache config.h.in~
exit 0
```

Anyhow I downloaded it here: https://github.com/google/googletest/archive/release-1.5.0.tar.gz

So I was able to compile protobuf 2.6.1 but ripple still fails with the same error.
I'm using boost 1.6.2 from homebrew. Is this also a problem?
`/bin/bash -c "BOOST_ROOT=/usr/local/Cellar/boost/1.62.0/include PROTOBUF_ROOT=/usr/local/include scons"`

**Comment by mellery451** [comment]
I don't understand why you are running `autogen.sh` - it says very clearly at the top of the file that it is used to generate the configure script and other files that they want to include in the distribution. In other words, it has already been run for this package. As indicated by our instructions AND the protobuf README, you should run `./configure` and then `make`. I have no doubt that autogen is having issues - it's probably only really intended to be run by the package maintainers, and I wouldn't necessarily expect this script to work long-term once the distribution package has been created. 

In any event, the gtest directory *is* there when you first unpack the directory - I think you are getting confused by the output of autogen in this case.

As for boost 1.62, we are not quite ready to completely bless that version. Some developers have success with it and a few others have reported issues. We can say confidently that 1.61 works fine for building on macos.

Please post the output from `scons` and/or `make` showing the current errors you are seeing.

**Comment by cserb** [comment]
The reason I had to use autogen was because I downloaded the "Source Code". Anyhow, the other packages contained everything and I was able to use ./configure directly.

The error message with protobuf 2.6.1 (compiled like described in the guide) is this:
```
⋊> ~/W/S/rippled on release ⨯ /bin/bash -c "BOOST_ROOT=/usr/local/Cellar/boost/1.62.0/include PROTOBUF_ROOT=/usr/local/include scons"                                                               19:43:42
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
protoc -Isrc/ripple/proto --cpp_out=build/proto src/ripple/proto/ripple.proto
clang++ -o build/clang.release/src/ripple/unity/app_ledger.o -c -Wall -frtti -std=c++14 -Wno-invalid-offsetof -Wno-mismatched-tags -Wno-deprecated-register -Wno-unused-local-typedefs -Wno-unknown-warning-option -isystem/usr/local/Cellar/boost/1.62.0/include -Wno-sign-compare -Wno-char-subscripts -Wno-format -g -Wno-redeclared-class-member -Wno-deprecated -Wno-deprecated-declarations -Wno-unused-variable -Wno-unused-function -O3 -fno-strict-aliasing -DOPENSSL_NO_SSL2 -DDEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER -DHAVE_USLEEP=1 -DSOCI_CXX_C11=1 -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS -DBOOST_NO_AUTO_PTR -DNO_LOG_UNHANDLED_EXCEPTIONS -DNDEBUG -DBOOST_ASIO_HAS_STD_ARRAY -D_FILE_OFFSET_BITS=64 -DBEAST_COMPILE_OBJECTIVE_CPP=1 -I/usr/local/Cellar/openssl/1.0.2j/include -Isrc -Isrc/beast -Isrc/beast/include -Isrc/beast/extras -Ibuild/proto -Isrc/soci/src -Isrc/soci/include -I/usr/local/include/src src/ripple/unity/app_ledger.cpp
In file included from src/ripple/unity/app_ledger.cpp:24:
In file included from src/ripple/app/ledger/AccountStateSF.cpp:22:
In file included from src/ripple/app/ledger/LedgerMaster.h:40:
build/proto/ripple.pb.h:9:10: fatal error: 'google/protobuf/stubs/common.h' file not found
#include <google/protobuf/stubs/common.h>
         ^
1 error generated.
scons: *** [build/clang.release/src/ripple/unity/app_ledger.o] Error 1
scons: building terminated because of errors.
```

**Comment by mellery451** [comment]
Does the file `/usr/local/include/google/protobuf/stubs/common.h` exist on your system and is it readable? I just want to confirm...if `make install` for protobuf succeeded, it should be there.

I think PROTOBUF_ROOT is used to point to a local (non installed) source tree for protobuf. If you have installed it in `/usr/local`, then I think it's not needed. Please try without this env var set.

**Comment by cserb** [comment]
I can confirm it's there and readable. Also I tried both with and without setting PROTOBUF_ROOT

**Comment by cserb** [comment]
I was finally able to compile it.
The problem was this line:
```
env.Append(CPPPATH=[env['PROTOBUF_ROOT'] + '/src',])
```
It was always looking into `/usr/local/inlcude/src` but everything it in `/usr/local/inlcude`
Creating a `src` symlink fixed the problem

**Comment by mellery451** [comment]
ok - that's interesting. I would have expected this all to work with the standard `/usr/local` installation location as long as `PROTOBUF_ROOT` is *not* set -- but you said you tried that, so I'm not sure what is going on. 

I would suggest moving forward that you either keep a separate build/source tree for protobuf and then set `PROTOBUF_ROOT` or, preferably, see if you can get it working with the installed protobuf in `/usr/local` *without* setting `PROTOBUF_ROOT`.  

That said, if you believe there are specific changes need to the `Sconstruct` file to support your use case, please feel free to suggest or submit a patch.

**Comment by cserb** [comment]
I have no knowledge about scons or c++, so making a pull request without understanding the context would not be a good idea :)

I would assume there is an issue with scons finding the protobuf folder because it clearly isn't working without setting `PROTOBUF_ROOT`

In the past those kind of issues would start appearing after major macOS updates. Thus I woudn't be surprised if this is somehow `macOS Sierra` related. If you are still on `10.11.x` it could explain why it works for you...

**Comment by vinniefalco** [comment]
Is this still an issue?

**Comment by cserb** [comment]
I can't tell. I'd have to reconstruct the same environment...

**Comment by vinniefalco** [comment]
Are you able to build on OS X now?

**Comment by cserb** [comment]
I was able to build before by making the changes described earlier in the discussion. Right now I don't have a mac and thus not able to try it again.

**Comment by JoeLoser** [comment]
I can build on OS X, but I had to use some workaround for a few Boost libraries (Context, Thread). In my installation of Boost 1.65.1, I had multithreaded libs, but the Sconstruct file seems to explicitly look for non-mt libs. Simply setting a symlink in my boost install such as:

```
ln -s libboost_context-mt.a libboost_context.a
ln -s libboost_thread-mt.a libboost_thread.a
```
It's certainly a bit of a hack and probably worth filing a separate Github issue for that.

**Comment by bachase** [comment]
Hi @JoeLoser!  The OS X build is not deprecated, just not officially supported since it is not part of regular CI. Nonetheless, I believe @mellery451, @scottschurr and @HowardHinnant regularly run it.  
https://github.com/ripple/rippled/tree/develop/Builds/XCode is the most update-to-date instructions, but are very close to deprecating `scons` build in favor of `cmake`.  I'm curious if you have similar linker issues using `cmake`.

The `npm` tests are deprecated (see #1943) and have been migrated to C++ unit tests, run via  `rippled -u` .

**Comment by JoeLoser** [comment]
Hey @bachase -- nice to see you again! 

Glad to hear others run it regularly. Funny that you suggest CMake. I originally started with that without searching for a build guide, but I ran into LTO issues that I couldn't solve. Have you seen then or before or have a good way to navigate this issue?

```
/usr/local/opt/llvm/bin/ld.lld: error: unknown argument: -dynamic
/usr/local/opt/llvm/bin/ld.lld: error: unknown argument: -arch
/usr/local/opt/llvm/bin/ld.lld: error: unknown argument: -search_paths_first
/usr/local/opt/llvm/bin/ld.lld: error: unknown argument: -framework
/usr/local/opt/llvm/bin/ld.lld: error: unknown argument: -framework
/usr/local/opt/llvm/bin/ld.lld: error: unknown emulation: acosx_version_min
/usr/local/opt/llvm/bin/ld.lld: error: unable to find library -lto_library
/usr/local/opt/llvm/bin/ld.lld: error: /usr/local/Cellar/llvm/5.0.0/lib/libLTO.dylib: invalid data encoding
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
From looking at the verbose output from Ninja, the important parts seem to be that we're using lld (`-fuse-ld=lld` present). It seems to be being up the correct library for using LLVM's LTO. Nonetheless, I also tried explicitly setting `DYLD_LIBRARY_PATH` to be the path to `libLTO.dylib` but that did not help. This isn't surprising as we're already getting the path to the LTO library correct, so I suspect it is something else.

For now, I may try disabling LTO in the builds to see if I can at least get up and going. But, if you have any insight on how to fix this, I'd love to hear. Once I can get it compiled with Clang 5, then I'll give the unit tests a go.

**Comment by mellery451** [comment]
I believe the regular macos users build with the AppleClang compiler that comes with xcode. It looks to me like you are using the homebrew llvm here - is this because you specifically need clang-5, or did something else about the AppleClang compiler not work for you? It's been a while since I tried building with the homebrew tools, but I seem to remember running into issues like what you are seeing.

**Comment by JoeLoser** [comment]
I am indeed using LLVM 5 from Homebrew. No particular reason for using Clang 5. I originally tried with AppleClang like you mentioned, but ran into the same LTO issues. For example, same error, just different paths:
```
/usr/local/opt/llvm/bin/ld.lld: error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib: invalid data encoding
```
I was pretty explicit about which C and C++ compiler for CMake to use, and it found them correctly. Here was my CMake invocation:
```
cmake -G Ninja -DCMAKE_CXX_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -DCMAKE_C_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ..
```

**Comment by mellery451** [comment]
hmm - you shouldn't have to work that hard to convince cmake to use the xcode compiler. On my system, CMake finds the xcode tools by default. Two suggestions come to mind (1) make sure you've done the xcode CLI tools install...or just re-run it (`xcode-select --install`)  and (2) if this homebrew llvm directory is in your path, I'd remove it. (If it's NOT in your path, then I'm unclear how cmake would be finding that linker...so we need to figure that out).

**Comment by mellery451** [comment]
if I had to guess, I'd speculate that scons and cmake have different methods for choosing a linker and scons finds one that works and cmake doesn't (?). It's also possible that the two tools pass different flags by default and the cmake ones confuse the homebrew-llvm linker. Those are just guesses. Yes, I think I will close this issue for now. Thanks @JoeLoser for the feedback.
