### ISSUE TITLE
Compile broken since af0ec2350ea53f0e9709a0c78f22f3b00e471429

### ISSUE THREAD

**Issue by nelisky** [ripple/rippled#148]
From commit af0ec2350ea53f0e9709a0c78f22f3b00e471429 on I can't compile on my ubuntu 12.10:

g++ -o build/obj/modules/ripple_app/ripple_app_pt8.o -c -O0 -pthread -Wno-invalid-offsetof -Wformat -g -DDEBUG -frtti -pthread -pthread -Wall -Wno-sign-compare -Wno-char-subscripts -I. -Ibuild/proto -ISubtrees -ISubtrees/leveldb -ISubtrees/leveldb/port -ISubtrees/leveldb/include -ISubtrees/beast -Isrc/cpp/ripple modules/ripple_app/ripple_app_pt8.cpp
In file included from modules/ripple_app/ripple_app.cpp:400:0,
                 from modules/ripple_app/ripple_app_pt8.cpp:8:
./src/cpp/ripple/LedgerMaster.cpp: In member function 'void ripple::LedgerMaster::asyncAccept(ripple::Ledger::pointer)':
./src/cpp/ripple/LedgerMaster.cpp:295:43: error: expected primary-expression before ')' token
./src/cpp/ripple/LedgerMaster.cpp:295:43: error: 'Writelog' was not declared in this scope
scons: **\* [build/obj/modules/ripple_app/ripple_app_pt8.o] Error 1
scons: building terminated because of errors.

**Comment by vinniefalco** [comment]
Obsolete
